### PR TITLE
Set up continuous integration & deployment with Travis

### PR DESCRIPTION
**Pull request by ErikBjare**
- For this to go into effect, we need to start using the `develop` branch as our default branch and use the `master` branch only as a place for builds of the website which GitHub will serve.
   - An example is [here](https://github.com/ActivityWatch/activitywatch.github.io/branches) where an identical setup is used for [activitywatch.net](http://activitywatch.net/).

### CODE REVIEW

**Comment by gorelhedin** [comment]
What do you intend to check with the continuous integration?

**Comment by ErikBjare** [comment]
@gorelhedin Not much being checked right now, it just builds the site and should then push the build to the right branch for GitHub to host it.

We might not need to switch default branch after all as it turns out that's only needed if the website is to be hosted on the organizations main site (as is the case for ActivityWatch).

**Comment by gorelhedin** [comment]
Ok. Sounds good if we don't need two branches.

**Comment by ErikBjare** [comment]
Well still need two branches, but no one will ever have to touch the gh-pages branch manually and they wont share any history.

**Pull request merged**
